# Generated by Django 2.0.4 on 2018-04-06 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bank',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('acc_no', models.IntegerField(max_length=6, primary_key=True, serialize=False)),
                ('bal', models.IntegerField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
