fo = open("hello.txt")
print("Name of the file - ",fo.name)
print("Is file closed or not - ",fo.closed)
print("Opening mode is - ",fo.mode)
print("The content of file as ")
print(fo.read())
fo.seek(0)
print("Again read the whole file")
print(fo.read())
fo.seek(0,0)
print("Now we will read 30 bytes of the file")
print(fo.read(30))
print("Now we will check the position in the file ")
print(fo.tell())
print("let's try something new ")
fo.seek(30,0)
print(fo.read)
print("file pointer position")
print(fo.tell())
fo.seek(0)
print("the file is ",fo.read())
print("Check what 1 offset does in file")
fo.seek(30,1)
print(fo.read())
print("Now check the what 2 offset does")
fo.seek(30,2)
print("position",fo.tell())
print(fo.read())
fo.close()
