#!C:\\Anaconda3\\python.exe

print("Content-type:text/html")
print("\n")

print("<!Doctype html>")
print("<html>")
print("<head>")
print("<link rel='stylesheet' type='text/css' href='/python1/css/main.css'>")
print("</head>")
print("<body>")
print("<p>")
print("*"*30)
print("</p>")
print("<br />")
print("<h1>Welcome to Python CGI Scripts</h1>")
print("<a href='/python1/'>HOME</a>")
print("<a href='/cgi-bin/pythoncgi1/hello.py'>Python-HELLO</a>")
print("<br />")
print("<p>")
print("*"*30)
print("</p>")
print("</body>")
print("</html>")