# Generated by Django 2.1.3 on 2018-11-16 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='hno',
            field=models.CharField(max_length=10),
        ),
    ]
