# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-02 01:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='event_blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=50,null=False)),
                ('description', models.CharField(max_length=300,null=False)),
                ('image', models.ImageField(null=True, upload_to='/static/upload')),
            ],
        ),
        migrations.CreateModel(
            name='gallary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_created=True)),
                ('name', models.CharField(max_length=50)),
                ('img', models.ImageField(null=True, upload_to='/static/upload')),
            ],
        ),
    ]
