# Generated by Django 2.0 on 2017-12-10 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email_id', models.CharField(max_length=50)),
                ('contact_no', models.IntegerField()),
                ('address', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='')),
            ],
        ),
    ]
